### ISSUE TITLE
提示

### ISSUE THREAD

**Issue by tl54577** [isszz/webman-sensitive#2]
isszz\sensitive\SensitiveException: The sensitive words file does not exist in \vendor\isszz\webman-sensitive\src\Sensitive.php:425

**Comment by isszz** [comment]
- 安装后提示的吗？检查下config/plugin/isszz/webman-sensitive/目录下是否有敏感词库。默认情况安装后悔会自动复制词库过去如果没有，看看权限是否有可写？
- 如果是自定义的词库文件，是文件找词库不到
- 是不是打包后运行的？


😅问题怎么关闭了。。。我只是回复了一下😁
